### PR TITLE
Wapp JWT Auth pull request

### PR DESCRIPTION
**Pull request by mwiru**
With this pull I jsut added an Auth blueprint, implemented user authentication with JWT, defined a few API resources, added a few rules to API endpoints, set up our migrations environment with alembic and modified a few classes and functions and corrected some logic.

### CODE REVIEW

**Comment by RrNn** [comment]
It sounds like a good implementation. U can go ahead an merge

**Comment by RrNn** [comment]
Lemme check the source code and see

**Comment by mwiru** [comment]
Thx much

**Comment by rogerokello** [comment]
Good work on the persistent features

**Comment by mwiru** [comment]
I need more help on refactoring

**Comment by rogerokello** [comment]
Let me try and see if I can chip in and help

**Pull request merged**
